name: setup_appwrite
description: Sets up appwrite for okaki.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.1

# Add regular dependencies here.
dependencies:
  dart_appwrite: ^8.0.0
  dotenv: ^4.1.0
  # path: ^1.8.0

dev_dependencies:
  appwrite: ^9.0.0
  lints: ^2.0.0
  test: ^1.21.0

assets:
  - .env
